version: '3.4'

services:
  mchapakazitodo:
    image: mchapakazitodo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
